### PR TITLE
Styling updates

### PR DESCRIPTION
**Pull request by jurebb**
Changes include:

- font change
- title redesign
- fix of logout button width
- small text fixes
- introduction of card-tag ui element
- less text, more tags and icons
    - also, removal of duplicate text, e.g. sport name for each event in sport details page 
- introduction of dimmed cards
    - idea is to have bright white card usually denote events, and dimmed cards sports
- sport details redesign
- event list redesign into a nx2 grid

### CODE REVIEW

**Comment by jurebb** [comment]
image

**Comment by jurebb** [comment]
image

**Comment by jurebb** [comment]
image

**Comment by jurebb** [comment]
image

**Comment by jurebb** [comment]
image

**Comment by jurebb** [comment]
image

**Review by mbrizic — APPROVED** [review]

**Pull request merged**
